on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_RECEIVE_DOMAIN: ${{ secrets.RECEIVE_DOMAIN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN_GITHUB_ACTIONS_ADMINISTRATOR }}
          aws-region: ap-northeast-1
      - run: terraform init
      - run: terraform apply -auto-approve
      - run: terraform output
